---
- name: Cambio de señal por docker_compose
  hosts: "{{ host }}"
  vars_files: vars.yml

  tasks:
  - name: Ejecucion de docker_compose
    shell: ansible-playbook -i "{{ inventario }}" site.yml --limit="{{ limit }}" --tags="docker_compose"
