---
- name: Cambio de linea
  hosts: 192.34.12.96
  vars_files: vars.yml

  tasks:
  - name: Cambiar puerto SSH
    lineinfile:
      path: /opt/dockerapps/manifests/AWX_PRUEBA_.bk
      regexp: '^(.*)"{{ path0 }}"'
      line: "{{ path }}"
    tags: change
